# Generated by Django 3.0.8 on 2020-09-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=20, null=True, unique=True)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
