# Generated by Django 3.0.8 on 2020-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_pizza_pizzalet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(8, 8), (10, 10), (12, 12)], default='8', null=True)),
            ],
        ),
    ]
