# Generated by Django 3.0.8 on 2020-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200919_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizzalets',
            field=models.ManyToManyField(blank=True, to='order.Pizzalet'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='order.Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.IntegerField(choices=[(8, 8), (10, 10), (12, 12)], default='8', null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
