# Generated by Django 3.0.8 on 2020-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200920_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Preparing', 'Order Preparing'), ('Order on its way', 'Order on its way')], default='Order Submitted', max_length=200, null=True),
        ),
    ]
