# Generated by Django 3.0.8 on 2020-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200920_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='qty',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
