# Generated by Django 3.0.8 on 2020-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200920_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='qty',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
