# Generated by Django 3.0.8 on 2020-09-20 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200920_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='qty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
