# Generated by Django 3.0.8 on 2020-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200920_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='qty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
