# Generated by Django 3.0.8 on 2020-09-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200920_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='barangay',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
