# Generated by Django 3.0.8 on 2020-09-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200920_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
