# Generated by Django 3.0.8 on 2020-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
