# Generated by Django 3.0.8 on 2020-09-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_pizza_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzalets',
        ),
        migrations.DeleteModel(
            name='Pizzalet',
        ),
    ]
