# Generated by Django 3.0.8 on 2020-09-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200926_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizzas',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.Pizza'),
            preserve_default=False,
        ),
    ]
